# Generated by Django 5.1.1 on 2024-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_activeintervalsbrs_booking_eventbrs_delete_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrs',
            name='sensor_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
